# Generated by Django 5.2.7 on 2025-10-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cta_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='post',
            name='cta_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
