# Generated by Django 5.2.7 on 2025-10-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_post_cta_label_post_cta_url_post_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
