# Generated by Django 5.2.7 on 2025-10-17 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_review_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={},
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='map_lat',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='map_lng',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='category',
            field=models.CharField(choices=[('ASOCIACION', 'Asociación y Guías'), ('GASTRONOMIA', 'Gastronomía'), ('TRANSPORTE', 'Transporte'), ('OPERADORES', 'Operadores Turísticos'), ('GENERAL', 'Redes Sociales y General')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(default='Sin Nombre', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
