# Generated by Django 5.2.7 on 2025-10-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_galleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='media_file_url',
            field=models.URLField(default='algo', max_length=512),
            preserve_default=False,
        ),
    ]
