# Generated by Django 5.2.7 on 2025-10-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_galleryitem_media_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='media_file_url',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
