# Generated by Django 5.2.7 on 2025-10-18 01:18

import cloudinary_storage.storage
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_alter_galleryitem_media_file_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['order', '-id']},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='media_file',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='places/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='contactinfo',
            index=models.Index(fields=['category', 'is_active'], name='tourism_con_categor_210e71_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryitem',
            index=models.Index(fields=['is_active', 'order'], name='tourism_gal_is_acti_1f9f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryitem',
            index=models.Index(fields=['media_type'], name='tourism_gal_media_t_c45cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['slug'], name='tourism_pla_slug_fbcd20_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['category', 'is_active'], name='tourism_pla_categor_4a70ce_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published', 'is_featured'], name='tourism_pos_is_publ_278a20_idx'),
        ),
    ]
