# Generated by Django 5.2.7 on 2026-07-13 20:22

import cloudinary_storage.storage
import django.core.validators
import tourism.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0008_alter_contactinfo_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='places/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), tourism.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='posts/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), tourism.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='reviews/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), tourism.validators.validate_file_size]),
        ),
    ]
