# Generated by Django 5.2.7 on 2026-07-19 14:11

import tourism.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0009_alter_media_image_alter_post_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_hours', models.CharField(default='08:00 - 18:00', max_length=50)),
                ('general_price', models.PositiveIntegerField(default=15)),
                ('park_fee_students', models.PositiveIntegerField(default=10)),
                ('park_fee_nationals', models.PositiveIntegerField(default=20)),
                ('park_fee_foreigners', models.PositiveIntegerField(default=100)),
                ('transport_camioneta_price', models.PositiveIntegerField(default=25)),
                ('transport_mototaxi_price', models.PositiveIntegerField(default=100)),
                ('camping_price_per_tent', models.PositiveIntegerField(default=10)),
                ('camping_text', models.TextField(blank=True, default='Vive la experiencia completa durmiendo bajo las estrellas. Puedes traer tu propia carpa o alquilar una en la comunidad.')),
                ('gastronomy_text', models.TextField(blank=True, default='Las comunarias preparan deliciosas comidas típicas criollas los fines de semana.')),
                ('gastronomy_note', models.CharField(blank=True, default='🔥 También contamos con alquiler de parrillas para que prepares tu propio asado.', max_length=255)),
                ('security_text', models.TextField(blank=True, default='Para tu seguridad y la conservación del área protegida, está terminantemente prohibido desviarse de los senderos marcados o ingresar a zonas restringidas sin un guía autorizado.')),
                ('whatsapp_group_url', models.URLField(blank=True, default='https://chat.whatsapp.com/EpzISekSBCe08kJh9lsqpx')),
                ('route_video_youtube_id', models.CharField(blank=True, default='rMBSyYd7JJE', max_length=30)),
                ('park_rules', models.JSONField(blank=True, default=tourism.models.default_park_rules)),
                ('activities', models.JSONField(blank=True, default=tourism.models.default_activities)),
                ('what_to_bring', models.JSONField(blank=True, default=tourism.models.default_what_to_bring)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Información del sitio',
                'verbose_name_plural': 'Información del sitio',
            },
        ),
    ]
