# Generated by Django 5.2.7 on 2026-07-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0010_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='key_features',
            field=models.JSONField(blank=True, default=list, help_text="Lista de características clave, ej: ['Fácil Acceso', 'Se puede nadar']"),
        ),
    ]
