# Generated by Django 5.2.7 on 2026-07-20 21:27

import cloudinary_storage.storage
import django.core.validators
import tourism.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0011_place_key_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='photo',
        ),
        migrations.AddField(
            model_name='review',
            name='attachment',
            field=models.FileField(blank=True, help_text='Opcional: Sube una foto o video (máx 50MB).', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='reviews/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'mp4', 'mov', 'avi', 'webm']), tourism.validators.validate_file_size]),
        ),
    ]
