# Generated by Django 5.2.7 on 2026-07-20 22:25

import tourism.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0012_remove_review_photo_review_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='activities_en',
            field=models.JSONField(blank=True, default=tourism.models.default_activities_en),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='camping_text_en',
            field=models.TextField(blank=True, default='Live the full experience sleeping under the stars. You can bring your own tent or rent one from the community.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gastronomy_note_en',
            field=models.CharField(blank=True, default='🔥 We also offer grill rentals so you can prepare your own barbecue.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gastronomy_text_en',
            field=models.TextField(blank=True, default='Local community members prepare delicious traditional Creole food on weekends.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='park_rules_en',
            field=models.JSONField(blank=True, default=tourism.models.default_park_rules_en),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='security_text_en',
            field=models.TextField(blank=True, default='For your safety and to help preserve this protected area, it is strictly forbidden to leave the marked trails or enter restricted zones without an authorized guide.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='what_to_bring_en',
            field=models.JSONField(blank=True, default=tourism.models.default_what_to_bring_en),
        ),
    ]
