# Generated by Django 5.2.7 on 2026-07-20 23:51

import tourism.models
from django.db import migrations, models


def migrate_transport_prices(apps, schema_editor):
    """Preserva los precios ya cargados en transport_options antes de borrar
    los campos viejos (transport_camioneta_price/transport_mototaxi_price)."""
    SiteSettings = apps.get_model('tourism', 'SiteSettings')
    for obj in SiteSettings.objects.all():
        obj.transport_options = [
            {"emoji": "🚙", "label": "Camioneta 4x4", "price": obj.transport_camioneta_price},
            {"emoji": "🛵", "label": "Mototaxi", "price": obj.transport_mototaxi_price},
        ]
        obj.save(update_fields=["transport_options"])


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0013_sitesettings_activities_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='route_start_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='route_start_text_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='transport_options',
            field=models.JSONField(blank=True, default=tourism.models.default_transport_options, help_text="Opciones de transporte mostradas en 'Cómo llegar', ej: [{'emoji': '🚙', 'label': 'Camioneta 4x4', 'price': 25}]"),
        ),
        migrations.RunPython(migrate_transport_prices, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sitesettings',
            name='transport_camioneta_price',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='transport_mototaxi_price',
        ),
    ]
