# Generated by Django 5.2.7 on 2026-07-21 00:44

import cloudinary_storage.storage
import django.core.validators
import tourism.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0014_remove_sitesettings_transport_camioneta_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='events/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), tourism.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='whatsapp_url',
            field=models.URLField(blank=True),
        ),
    ]
