# Generated by Django 5.2.7 on 2026-07-21 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0015_event_image_event_is_featured_event_whatsapp_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Edición'), ('delete', 'Eliminación')], max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null si el usuario fue borrado después de la acción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de actividad',
                'verbose_name_plural': 'Bitácora de actividad',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='tourism_act_created_034218_idx'), models.Index(fields=['model_name'], name='tourism_act_model_n_4ce704_idx'), models.Index(fields=['actor'], name='tourism_act_actor_i_da8e38_idx')],
            },
        ),
    ]
